DROP TABLE IF EXISTS workouts_exercises CASCADE;
DROP TABLE IF EXISTS workouts_users CASCADE;
DROP TABLE IF EXISTS workouts CASCADE;
DROP TABLE IF EXISTS exercise CASCADE;
DROP TABLE IF EXISTS users CASCADE;