// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Exercise struct {
	ID                int64          `json:"id"`
	Weight            sql.NullInt32  `json:"weight"`
	Reps              sql.NullInt32  `json:"reps"`
	TimeBetweenReps   sql.NullInt32  `json:"time_between_reps"`
	Explanation       sql.NullString `json:"explanation"`
	RequiredEquipment sql.NullString `json:"required_equipment"`
	MuscleArea        sql.NullString `json:"muscle_area"`
}

type User struct {
	ID        int64        `json:"id"`
	FirstName string       `json:"first_name"`
	LastName  string       `json:"last_name"`
	CreatedAt sql.NullTime `json:"created_at"`
	Coach     bool         `json:"coach"`
	Goal      string       `json:"goal"`
}

type Workout struct {
	ID           int64         `json:"id"`
	TimeEstimate sql.NullInt32 `json:"time_estimate"`
}

type WorkoutsExercise struct {
	ExerciseID sql.NullInt64 `json:"exercise_id"`
	WorkoutID  sql.NullInt64 `json:"workout_id"`
}

type WorkoutsUser struct {
	WorkoutID sql.NullInt64 `json:"workout_id"`
	UserID    sql.NullInt64 `json:"user_id"`
}
